# Generated by Django 5.0.1 on 2024-06-08 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActaTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tipo de Acta")),
            ],
            options={
                "verbose_name": "Tipo de Acta",
                "verbose_name_plural": "Tipos de Actas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Clases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Clase")),
                (
                    "subname",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Subclase"
                    ),
                ),
            ],
            options={
                "verbose_name": "Clase",
                "verbose_name_plural": "Clases",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CODPROV",
                    models.CharField(max_length=2, verbose_name="Código de Provincia"),
                ),
                (
                    "NOMPROV",
                    models.CharField(max_length=20, verbose_name="Nombre de Provincia"),
                ),
                (
                    "CODDEPTO",
                    models.CharField(
                        max_length=3, verbose_name="Código de Departamento"
                    ),
                ),
                (
                    "NOMDEPTO",
                    models.CharField(
                        max_length=30, verbose_name="Nombre de Departamento"
                    ),
                ),
                (
                    "CODMUNI",
                    models.CharField(max_length=4, verbose_name="Código de Municipio"),
                ),
                (
                    "NOMMUNI",
                    models.CharField(max_length=30, verbose_name="Nombre de Municipio"),
                ),
                (
                    "CODLOC",
                    models.CharField(max_length=3, verbose_name="Código de Localidad"),
                ),
                (
                    "CODAGLO",
                    models.CharField(
                        max_length=4, verbose_name="Código de Aglomerado"
                    ),
                ),
                (
                    "NOMLOC",
                    models.CharField(max_length=30, verbose_name="Nombre de Localidad"),
                ),
            ],
            options={
                "verbose_name": "Localidad",
                "verbose_name_plural": "Localidades",
                "ordering": ["CODPROV", "CODDEPTO", "CODMUNI", "CODLOC"],
            },
        ),
        migrations.CreateModel(
            name="Rubros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Rubro")),
            ],
            options={
                "verbose_name": "Rubro",
                "verbose_name_plural": "Rubros",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Titulos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Título")),
                (
                    "abreviation",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Abreviación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Título",
                "verbose_name_plural": "Títulos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Unidad")),
            ],
            options={
                "verbose_name": "Unidad",
                "verbose_name_plural": "Unidades",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Uvis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(blank=True, null=True, verbose_name="Fecha"),
                ),
                (
                    "valor",
                    models.FloatField(blank=True, null=True, verbose_name="Valor"),
                ),
            ],
            options={
                "verbose_name": "Uvi",
                "verbose_name_plural": "Uvis",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="ActaMedicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acta", models.PositiveIntegerField(verbose_name="N° Acta")),
                ("periodo", models.DateField(verbose_name="Periodo de medición")),
                (
                    "registro",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "ultima_modificacion",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Fecha y hora de última modificación",
                    ),
                ),
                (
                    "ultimo_editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actas_modificadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Último usuario editor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cargado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta de Medición",
                "verbose_name_plural": "Actas de Medición",
            },
        ),
        migrations.CreateModel(
            name="Certificados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expediente",
                    models.CharField(max_length=30, verbose_name="Expediente"),
                ),
                ("uvi", models.FloatField(verbose_name="UVIs del Certificado")),
                (
                    "uvi_acum",
                    models.FloatField(default=0, verbose_name="Cant UVIs acumulados"),
                ),
                (
                    "avance_acum_proy",
                    models.FloatField(
                        default=0, verbose_name="Avance proyectado acumulado (%)"
                    ),
                ),
                (
                    "avance_acum_med",
                    models.FloatField(
                        default=0, verbose_name="Avance real acumulado (%)"
                    ),
                ),
                (
                    "coef_avance",
                    models.BooleanField(default=False, verbose_name="Coef. Avance (%)"),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora de creación"
                    ),
                ),
                (
                    "ultima_modificacion",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Fecha y hora de última modificación",
                    ),
                ),
                (
                    "acta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.actamedicion",
                        verbose_name="Acta de Medición",
                    ),
                ),
                (
                    "cargaCert",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cargado por",
                    ),
                ),
                (
                    "ultimo_editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados_modificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Último usuario editor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["acta__obra", "acta__acta"],
            },
        ),
        migrations.CreateModel(
            name="EmpresaPoliza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa",
                    models.CharField(
                        max_length=50, verbose_name="Nombre de empresa aseguradora"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Domicilio"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "creaEmpresa",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Empresa creada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aseguradora",
                "verbose_name_plural": "Aseguradoras",
                "ordering": ["empresa"],
            },
        ),
        migrations.CreateModel(
            name="Inspectores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombres")),
                ("surname", models.CharField(max_length=200, verbose_name="Apellidos")),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "telephone",
                    models.CharField(max_length=50, verbose_name="Teléfono"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Correo")),
                (
                    "fullname",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        null=True,
                        verbose_name="Inspector",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "titulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.titulos",
                        verbose_name="Título",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspector",
                "verbose_name_plural": "Inspectores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Instituciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Institución")),
                (
                    "geometry",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Georeferencia",
                    ),
                ),
                (
                    "clase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.clases",
                        verbose_name="Tipo de Institución",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.location",
                        verbose_name="Ubicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Empresas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombres")),
                (
                    "propietario",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Propietario",
                    ),
                ),
                (
                    "representante_tecnico",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Representante Técnico",
                    ),
                ),
                (
                    "calle",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Calle"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Correo"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.location",
                        verbose_name="Ubicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Obras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expedientes",
                    models.CharField(max_length=30, verbose_name="Expediente"),
                ),
                (
                    "codObra",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        null=True,
                        verbose_name="Cod. Obra",
                    ),
                ),
                ("inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "plazo",
                    models.IntegerField(verbose_name="Plazo Contractual (días)"),
                ),
                (
                    "vencimiento_contractual",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimiento Contractual"
                    ),
                ),
                (
                    "nombre_obra",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Carátula Obra",
                    ),
                ),
                (
                    "monto_contrato",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Monto de contrato ($)"
                    ),
                ),
                (
                    "fecha_cotrato",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de contrato"
                    ),
                ),
                (
                    "monto_uvi",
                    models.FloatField(verbose_name="Monto de contrato (UVIS)"),
                ),
                (
                    "valor_uvi_contrato",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Valor UVI contrato"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.empresas",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.instituciones",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "uvi",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.uvis",
                        verbose_name="Uvi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obra",
                "verbose_name_plural": "Obras",
                "ordering": ["institucion"],
            },
        ),
        migrations.CreateModel(
            name="Memorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codMem",
                    models.CharField(
                        editable=False,
                        max_length=200,
                        unique=True,
                        verbose_name="Cod. Memoria",
                    ),
                ),
                (
                    "memoria",
                    models.TextField(blank=True, null=True, verbose_name="Memoria"),
                ),
                (
                    "resumen",
                    models.TextField(blank=True, null=True, verbose_name="Resumen"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="static/images",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cargado por",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.obras",
                        verbose_name="Obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memoria",
                "verbose_name_plural": "Memorias",
                "ordering": ["obra"],
            },
        ),
        migrations.CreateModel(
            name="DispoInspector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispo", models.CharField(max_length=30, verbose_name="Disposición")),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "observacion",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cargado por",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.inspectores",
                        verbose_name="Inspector",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.obras",
                        verbose_name="Obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disp Inspector",
                "verbose_name_plural": "Disp Inspectores",
                "ordering": ["inspector"],
            },
        ),
        migrations.CreateModel(
            name="ActasObras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha aplicación Acta"
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(default=1, verbose_name="Nro Orden"),
                ),
                (
                    "dispo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Disposición",
                    ),
                ),
                (
                    "codActa",
                    models.CharField(
                        editable=False,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Cod. Acta",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.actatipo",
                        verbose_name="Tipo de Acta",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.obras",
                        verbose_name="Obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta obra",
                "verbose_name_plural": "Actas obras",
                "ordering": ["obra"],
            },
        ),
        migrations.CreateModel(
            name="ActasInicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cargado por",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.obras",
                        verbose_name="Obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta de inicio",
                "verbose_name_plural": "Actas de inicio",
                "ordering": ["obra"],
            },
        ),
        migrations.AddField(
            model_name="actamedicion",
            name="obra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.obras",
                verbose_name="Obra",
            ),
        ),
        migrations.CreateModel(
            name="Polizas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codPol",
                    models.CharField(
                        editable=False,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Cod. Poliza",
                    ),
                ),
                (
                    "tiene_poliza",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Presenta póliza de sustitución?",
                    ),
                ),
                (
                    "acta_fondo_reparo",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Póliza de sustitución Fondo de Reparo",
                    ),
                ),
                (
                    "poliza_sustitucion",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="N° Póliza Fondo de Reparo"
                    ),
                ),
                (
                    "monto_asegurado",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Monto asegurado"
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(default=1, verbose_name="Nro Orden"),
                ),
                (
                    "obervacion",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                (
                    "empresa_poliza",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.empresapoliza",
                        verbose_name="Empresa aseguradora",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.obras",
                        verbose_name="Obra",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poliza",
                "verbose_name_plural": "Polizas",
                "ordering": ["obra"],
            },
        ),
        migrations.CreateModel(
            name="Presupuestos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_presupuesto",
                    models.DateField(null=True, verbose_name="Fecha Presupuesto"),
                ),
                (
                    "fecha_oferta",
                    models.DateField(null=True, verbose_name="Fecha Oferta"),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.obras",
                        verbose_name="Obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["obra"],
            },
        ),
        migrations.CreateModel(
            name="Subrubros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Item")),
                (
                    "rubro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.rubros",
                        verbose_name="Rubro",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.unidades",
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["rubro", "name"],
            },
        ),
        migrations.CreateModel(
            name="PresupuestosSubrubros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rubro_ok",
                    models.BooleanField(default=False, verbose_name="Es Rubro?"),
                ),
                ("nro_rubro", models.CharField(max_length=2, verbose_name="No. Rubro")),
                (
                    "nro_item",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="No. Item"
                    ),
                ),
                (
                    "full_item",
                    models.CharField(
                        editable=False, max_length=200, verbose_name="Item"
                    ),
                ),
                (
                    "cantidad",
                    models.FloatField(blank=True, null=True, verbose_name="Cantidad"),
                ),
                (
                    "precio_unitario_presupuesto",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Precio Unit Presup"
                    ),
                ),
                (
                    "precio_total_presupuesto",
                    models.FloatField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Precio Total",
                    ),
                ),
                (
                    "incidencias_presupuesto",
                    models.FloatField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Incidencias",
                    ),
                ),
                (
                    "precio_unitario_oferta",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Precio Unit Oferta"
                    ),
                ),
                (
                    "precio_total_oferta",
                    models.FloatField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Precio Total",
                    ),
                ),
                (
                    "incidencias_oferta",
                    models.FloatField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Incidencias",
                    ),
                ),
                (
                    "uvi_oferta",
                    models.FloatField(
                        blank=True, editable=False, null=True, verbose_name="Uvi"
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.presupuestos",
                        verbose_name="Presupuesto",
                    ),
                ),
                (
                    "rubro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.rubros",
                        verbose_name="Rubro",
                    ),
                ),
                (
                    "subrubro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.subrubros",
                        verbose_name="Item",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.unidades",
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["presupuesto"],
            },
        ),
        migrations.AddField(
            model_name="presupuestos",
            name="subrubro",
            field=models.ManyToManyField(
                blank=True,
                through="mioc.PresupuestosSubrubros",
                to="mioc.subrubros",
                verbose_name="Items",
            ),
        ),
        migrations.AddField(
            model_name="presupuestos",
            name="uvi",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.uvis",
                verbose_name="Uvi",
            ),
        ),
    ]
