# Generated by Django 5.0.1 on 2024-03-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="localidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CODPROV",
                    models.CharField(max_length=2, verbose_name="Código de Provincia"),
                ),
                (
                    "NOMPROV",
                    models.CharField(max_length=20, verbose_name="Nombre de Provincia"),
                ),
                (
                    "CODDEPTO",
                    models.CharField(
                        max_length=3, verbose_name="Código de Departamento"
                    ),
                ),
                (
                    "NOMDEPTO",
                    models.CharField(
                        max_length=30, verbose_name="Nombre de Departamento"
                    ),
                ),
                (
                    "CODMUNI",
                    models.CharField(max_length=4, verbose_name="Código de Municipio"),
                ),
                (
                    "NOMMUNI",
                    models.CharField(max_length=30, verbose_name="Nombre de Municipio"),
                ),
                (
                    "CODLOC",
                    models.CharField(max_length=3, verbose_name="Código de Localidad"),
                ),
                (
                    "CODAGLO",
                    models.CharField(
                        max_length=4, verbose_name="Código de Aglomerado"
                    ),
                ),
                (
                    "NOMLOC",
                    models.CharField(max_length=30, verbose_name="Nombre de Localidad"),
                ),
            ],
            options={
                "verbose_name": "Localidad",
                "verbose_name_plural": "Localidades",
                "ordering": ["CODPROV", "CODDEPTO", "CODMUNI", "CODLOC"],
            },
        ),
    ]
