# Generated by Django 5.0.1 on 2024-03-04 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Clase")),
                (
                    "subname",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Subclase"
                    ),
                ),
            ],
            options={
                "verbose_name": "Clase",
                "verbose_name_plural": "Clases",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Inspectores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombres")),
                ("surname", models.CharField(max_length=200, verbose_name="Apellidos")),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "telephone",
                    models.CharField(max_length=50, verbose_name="Teléfono"),
                ),
                ("mail", models.EmailField(max_length=254, verbose_name="Correo")),
            ],
            options={
                "verbose_name": "Inspector",
                "verbose_name_plural": "Inspectores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CODPROV",
                    models.CharField(max_length=2, verbose_name="Código de Provincia"),
                ),
                (
                    "NOMPROV",
                    models.CharField(max_length=20, verbose_name="Nombre de Provincia"),
                ),
                (
                    "CODDEPTO",
                    models.CharField(
                        max_length=3, verbose_name="Código de Departamento"
                    ),
                ),
                (
                    "NOMDEPTO",
                    models.CharField(
                        max_length=30, verbose_name="Nombre de Departamento"
                    ),
                ),
                (
                    "CODMUNI",
                    models.CharField(max_length=4, verbose_name="Código de Municipio"),
                ),
                (
                    "NOMMUNI",
                    models.CharField(max_length=30, verbose_name="Nombre de Municipio"),
                ),
                (
                    "CODLOC",
                    models.CharField(max_length=3, verbose_name="Código de Localidad"),
                ),
                (
                    "CODAGLO",
                    models.CharField(
                        max_length=4, verbose_name="Código de Aglomerado"
                    ),
                ),
                (
                    "NOMLOC",
                    models.CharField(max_length=30, verbose_name="Nombre de Localidad"),
                ),
            ],
            options={
                "verbose_name": "Localidad",
                "verbose_name_plural": "Localidades",
                "ordering": ["CODPROV", "CODDEPTO", "CODMUNI", "CODLOC"],
            },
        ),
        migrations.CreateModel(
            name="Titulos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Título")),
                (
                    "abreviation",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Abreviación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Título",
                "verbose_name_plural": "Títulos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Instituciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Institución")),
                (
                    "geometry",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Georeferencia",
                    ),
                ),
                (
                    "clase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.clases",
                        verbose_name="Tipo de Institución",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.location",
                        verbose_name="Ubicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Obras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "plazo",
                    models.IntegerField(verbose_name="Plazo Contractual (días)"),
                ),
                (
                    "vencimiento_contractual",
                    models.DateField(
                        editable=False, verbose_name="Vencimiento Contractual"
                    ),
                ),
                (
                    "ampliacion_1",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="1ra Ampliación (días)"
                    ),
                ),
                (
                    "vencimiento_ampliacion_1",
                    models.DateField(
                        editable=False,
                        verbose_name="Vencimiento 1ra Ampliación Contractual",
                    ),
                ),
                (
                    "ampliacion_2",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="2da Ampliación (días)"
                    ),
                ),
                (
                    "vencimiento_ampliacion_2",
                    models.DateField(
                        editable=False,
                        verbose_name="Vencimiento 2da Ampliación Contractual",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.inspectores",
                        verbose_name="Inspector",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.instituciones",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obra",
                "verbose_name_plural": "Obras",
                "ordering": ["institucion"],
            },
        ),
        migrations.AddField(
            model_name="inspectores",
            name="titulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.titulos",
                verbose_name="Título",
            ),
        ),
    ]
