# Generated by Django 5.0.1 on 2024-07-10 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificadosAF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expediente",
                    models.CharField(max_length=30, verbose_name="Expediente"),
                ),
                ("monto", models.FloatField(verbose_name="Monto del Certificado")),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora de creación"
                    ),
                ),
                (
                    "ultima_modificacion",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Fecha y hora de última modificación",
                    ),
                ),
                (
                    "cargaCert",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cargado por",
                    ),
                ),
                (
                    "dispo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.anticipofinanciero",
                        verbose_name="Disposición de aceptación AF",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado AF",
                "verbose_name_plural": "Certificados Af",
                "ordering": ["dispo"],
            },
        ),
    ]
