# Generated by Django 5.0.1 on 2024-03-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obras",
            name="vencimiento_ampliacion_1",
            field=models.DateField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Vencimiento 1ra Ampliación Contractual",
            ),
        ),
        migrations.AlterField(
            model_name="obras",
            name="vencimiento_ampliacion_2",
            field=models.DateField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Vencimiento 2da Ampliación Contractual",
            ),
        ),
    ]
