# Generated by Django 5.0.1 on 2024-06-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obras",
            name="monto_uvi",
            field=models.FloatField(verbose_name="Monto de contrato (UVIS)"),
        ),
    ]
