# Generated by Django 5.0.1 on 2024-06-04 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actamedicion",
            name="registro",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de registro",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="actamedicion",
            name="periodo",
            field=models.DateField(verbose_name="Periodo de medición"),
        ),
    ]
