# Generated by Django 5.0.1 on 2024-06-04 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0002_actamedicion_registro_alter_actamedicion_periodo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actamedicion",
            options={
                "verbose_name": "Acta de Medición",
                "verbose_name_plural": "Actas de Medición",
            },
        ),
        migrations.AlterModelOptions(
            name="certificados",
            options={
                "ordering": ["acta__obra", "acta__acta"],
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
            },
        ),
        migrations.RenameField(
            model_name="actamedicion",
            old_name="acta_nro",
            new_name="acta",
        ),
        migrations.RemoveField(
            model_name="certificados",
            name="codCert",
        ),
        migrations.RemoveField(
            model_name="certificados",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="certificados",
            name="fecha_acta",
        ),
        migrations.RemoveField(
            model_name="certificados",
            name="nro_cert",
        ),
        migrations.RemoveField(
            model_name="certificados",
            name="obra",
        ),
        migrations.RemoveField(
            model_name="certificados",
            name="periodo",
        ),
        migrations.AddField(
            model_name="actamedicion",
            name="ultima_modificacion",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                verbose_name="Fecha y hora de última modificación",
            ),
        ),
        migrations.AddField(
            model_name="actamedicion",
            name="ultimo_editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actas_modificadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Último usuario editor",
            ),
        ),
        migrations.AddField(
            model_name="certificados",
            name="acta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.actamedicion",
                verbose_name="Acta de Medición",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="certificados",
            name="uvi",
            field=models.FloatField(verbose_name="UVIs del Certificado"),
        ),
    ]
