# Generated by Django 5.0.1 on 2024-06-01 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0002_alter_obras_monto_uvi"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificados",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha y hora de creación",
            ),
            preserve_default=False,
        ),
    ]
