# Generated by Django 5.0.1 on 2024-06-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0002_anticipofinanciero"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anticipofinanciero",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Anticipo financiero",
                "verbose_name_plural": "Anticipos financieros",
            },
        ),
        migrations.AddField(
            model_name="anticipofinanciero",
            name="dispo",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Disposición"
            ),
        ),
        migrations.AddField(
            model_name="anticipofinanciero",
            name="fecha",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha"),
        ),
    ]
