# Generated by Django 5.0.1 on 2024-07-16 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0002_certificadosaf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificadosaf",
            name="dispo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.anticipofinanciero",
                verbose_name="Obra",
            ),
        ),
    ]
