# Generated by Django 5.0.1 on 2024-03-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0002_rename_localidad_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Clase")),
                (
                    "subname",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Subclase"
                    ),
                ),
            ],
            options={
                "verbose_name": "Clase",
                "verbose_name_plural": "Clases",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Instituciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Institución")),
                (
                    "geometry",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Georeferencia",
                    ),
                ),
                (
                    "clase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.clases",
                        verbose_name="Tipo de Institución",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.location",
                        verbose_name="Ubicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
                "ordering": ["name"],
            },
        ),
    ]
