# Generated by Django 5.0.1 on 2024-03-04 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0003_uvis_presupuestos_obras_uvi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Rubro")),
            ],
            options={
                "verbose_name": "Rubro",
                "verbose_name_plural": "Rubros",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="presupuestos",
            name="fecha",
            field=models.DateField(null=True, verbose_name="Fecha"),
        ),
        migrations.AddField(
            model_name="presupuestos",
            name="uvi",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.uvis",
                verbose_name="Uvi",
            ),
        ),
        migrations.CreateModel(
            name="Subrubros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Subrubro")),
                (
                    "rubro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.rubros",
                        verbose_name="Rubro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subrubro",
                "verbose_name_plural": "Subrubros",
                "ordering": ["rubro", "name"],
            },
        ),
        migrations.CreateModel(
            name="PresupuestosSubrubros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_rubro", models.CharField(max_length=2, verbose_name="No. Rubro")),
                ("nro_item", models.CharField(max_length=3, verbose_name="No. Item")),
                (
                    "full_item",
                    models.CharField(
                        editable=False, max_length=200, verbose_name="Item"
                    ),
                ),
                ("unidad", models.CharField(max_length=10, verbose_name="Unidad")),
                ("cantidad", models.FloatField(verbose_name="Cantidad")),
                ("precio_unitario", models.FloatField(verbose_name="Precio Unitario")),
                (
                    "precio_total",
                    models.FloatField(editable=False, verbose_name="Precio Total"),
                ),
                (
                    "precio_rubro",
                    models.FloatField(editable=False, verbose_name="Precio Rubro"),
                ),
                (
                    "incidencias",
                    models.FloatField(editable=False, verbose_name="Incidencias"),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.presupuestos",
                        verbose_name="Presupuesto",
                    ),
                ),
                (
                    "subrubro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.subrubros",
                        verbose_name="Subrubro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["presupuesto"],
            },
        ),
        migrations.AddField(
            model_name="presupuestos",
            name="subrubro",
            field=models.ManyToManyField(
                blank=True,
                through="mioc.PresupuestosSubrubros",
                to="mioc.subrubros",
                verbose_name="Items",
            ),
        ),
    ]
