# Generated by Django 5.0.1 on 2024-07-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0003_alter_polizas_tiene_poliza"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polizas",
            name="tiene_poliza",
            field=models.BooleanField(
                null=True, verbose_name="Presenta póliza de sustitución?"
            ),
        ),
    ]
