# Generated by Django 5.0.1 on 2024-06-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0003_alter_anticipofinanciero_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anticipofinanciero",
            name="anticipo",
            field=models.BooleanField(default=False, verbose_name="Anticipo"),
        ),
        migrations.AlterField(
            model_name="anticipofinanciero",
            name="porcentaje",
            field=models.FloatField(blank=True, null=True, verbose_name="Porcentaje"),
        ),
    ]
