# Generated by Django 5.0.1 on 2024-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0004_alter_polizas_tiene_poliza"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresapoliza",
            name="cuit",
            field=models.CharField(max_length=11, verbose_name="CUIT"),
        ),
    ]
