# Generated by Django 5.0.1 on 2024-03-04 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0004_rubros_presupuestos_fecha_presupuestos_uvi_subrubros_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuestossubrubros",
            name="rubro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.rubros",
                verbose_name="Rubro",
            ),
        ),
    ]
