# Generated by Django 5.0.1 on 2024-07-16 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0004_alter_certificadosaf_expediente"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificadosaf",
            name="fecha",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha"
            ),
            preserve_default=False,
        ),
    ]
