# Generated by Django 5.0.1 on 2024-03-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0005_presupuestossubrubros_rubro"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuestossubrubros",
            name="rubro_ok",
            field=models.BooleanField(default=False, verbose_name="Es Rubro?"),
        ),
    ]
