# Generated by Django 5.0.1 on 2024-06-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0005_alter_anticipofinanciero_anticipo_estructuras"),
    ]

    operations = [
        migrations.AddField(
            model_name="estructuras",
            name="fecha",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha"),
        ),
    ]
