# Generated by Django 5.0.1 on 2024-07-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0005_certificadosaf_fecha"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificadosaf",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Certificado AF",
                "verbose_name_plural": "Certificados Af",
            },
        ),
        migrations.AddField(
            model_name="certificadosaf",
            name="uvi",
            field=models.FloatField(default=0, verbose_name="UVIs"),
            preserve_default=False,
        ),
    ]
