# Generated by Django 5.0.1 on 2024-03-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0006_presupuestossubrubros_rubro_ok"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="presupuestos",
            options={
                "ordering": ["obra"],
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
            },
        ),
    ]
