# Generated by Django 5.0.1 on 2024-07-16 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0006_alter_certificadosaf_options_certificadosaf_uvi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="dispoCertAF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispo",
                    models.CharField(
                        max_length=30, verbose_name="Disposición Aprueba Certificado AF"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha Dispo")),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora de creación"
                    ),
                ),
                (
                    "cargaCert",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cargado por",
                    ),
                ),
                (
                    "certificado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.certificadosaf",
                        verbose_name="Certificado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disposición Certificado AF",
                "verbose_name_plural": "Disposiciones Certificados AF",
                "ordering": ["-fecha"],
            },
        ),
    ]
