# Generated by Django 5.0.1 on 2024-07-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0007_dispocertaf"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispocertaf",
            name="observacion",
            field=models.TextField(blank=True, null=True, verbose_name="Observación"),
        ),
    ]
