# Generated by Django 5.0.1 on 2024-03-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0007_alter_presupuestos_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="cantidad",
            field=models.FloatField(blank=True, null=True, verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="nro_item",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="No. Item"
            ),
        ),
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="precio_unitario",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Precio Unitario"
            ),
        ),
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="unidad",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Unidad"
            ),
        ),
    ]
