# Generated by Django 5.0.1 on 2024-07-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0009_alter_anticipofinanciero_anticipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anticipofinanciero",
            name="anticipo",
            field=models.BooleanField(default=None, null=True, verbose_name="Anticipo"),
        ),
    ]
