# Generated by Django 5.0.1 on 2024-03-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mioc",
            "0010_rename_precio_rubro_presupuestossubrubros_precio_rubro_oferta_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="precio_unitario_oferta",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="Precio Unitario"
            ),
        ),
    ]
