# Generated by Django 5.0.1 on 2024-07-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0010_alter_facturasaf_comprobante_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturasaf",
            name="cuit",
            field=models.CharField(max_length=11, verbose_name="CUIT Empresa"),
        ),
    ]
