# Generated by Django 5.0.1 on 2024-03-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0011_alter_presupuestossubrubros_precio_unitario_oferta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="presupuestossubrubros",
            old_name="incidencias",
            new_name="incidencias_oferta",
        ),
        migrations.AddField(
            model_name="presupuestossubrubros",
            name="incidencias_presupuesto",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="Incidencias"
            ),
        ),
    ]
