# Generated by Django 5.0.1 on 2024-03-04 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mioc",
            "0012_rename_incidencias_presupuestossubrubros_incidencias_oferta_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Ofertas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(null=True, verbose_name="Fecha")),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.presupuestos",
                        verbose_name="Presupuesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta",
                "verbose_name_plural": "Ofertas",
                "ordering": ["presupuesto"],
            },
        ),
    ]
