# Generated by Django 5.0.1 on 2024-07-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0013_obras_fecha_dispo"),
    ]

    operations = [
        migrations.AddField(
            model_name="obras",
            name="dispo_contrato",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Dispo. Contrato",
            ),
        ),
    ]
