# Generated by Django 5.0.1 on 2024-03-04 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0013_ofertas"),
    ]

    operations = [
        migrations.AddField(
            model_name="ofertas",
            name="uvi",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.uvis",
                verbose_name="Uvi",
            ),
        ),
    ]
