# Generated by Django 5.0.1 on 2024-07-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0014_alter_facturasaf_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificados",
            name="avance_acum_med",
        ),
        migrations.RemoveField(
            model_name="certificados",
            name="avance_acum_proy",
        ),
        migrations.RemoveField(
            model_name="certificados",
            name="coef_avance",
        ),
        migrations.RemoveField(
            model_name="certificados",
            name="uvi",
        ),
        migrations.RemoveField(
            model_name="certificados",
            name="uvi_acum",
        ),
    ]
