# Generated by Django 5.0.1 on 2024-03-05 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0014_ofertas_uvi"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuestossubrubros",
            name="uvi_oferta",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.uvis",
                verbose_name="Uvi",
            ),
        ),
        migrations.CreateModel(
            name="PlanTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.presupuestos",
                        verbose_name="Presupuesto",
                    ),
                ),
            ],
        ),
    ]
