# Generated by Django 5.0.1 on 2024-03-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0015_presupuestossubrubros_uvi_oferta_plantrabajo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlanTrabajo",
        ),
    ]
