# Generated by Django 5.0.1 on 2024-07-09 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0015_alter_obras_dispo_contrato_alter_obras_fecha_dispo"),
    ]

    operations = [
        migrations.AddField(
            model_name="estructuras",
            name="inspector",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.inspectores",
                verbose_name="Inspector",
            ),
        ),
    ]
