# Generated by Django 5.0.1 on 2024-07-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0015_remove_certificados_avance_acum_med_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actamedicionvalidacion",
            name="avance_acum_med",
            field=models.FloatField(
                default=0, verbose_name="Avance real acumulado (%)"
            ),
        ),
        migrations.AddField(
            model_name="actamedicionvalidacion",
            name="avance_acum_proy",
            field=models.FloatField(
                default=0, verbose_name="Avance proyectado acumulado (%)"
            ),
        ),
        migrations.AddField(
            model_name="actamedicionvalidacion",
            name="coef_avance",
            field=models.BooleanField(default=False, verbose_name="Coef. Avance (%)"),
        ),
        migrations.AddField(
            model_name="actamedicionvalidacion",
            name="uvi",
            field=models.FloatField(default=0, verbose_name="UVIs del Certificado"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actamedicionvalidacion",
            name="uvi_acum",
            field=models.FloatField(default=0, verbose_name="Cant UVIs acumulados"),
        ),
    ]
