# Generated by Django 5.0.1 on 2024-03-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0016_delete_plantrabajo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="presupuestossubrubros",
            name="precio_rubro_oferta",
        ),
        migrations.RemoveField(
            model_name="presupuestossubrubros",
            name="precio_rubro_presupuesto",
        ),
    ]
