# Generated by Django 5.0.1 on 2024-07-19 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0016_actamedicionvalidacion_avance_acum_med_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="dispo_plan_trabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrumento",
                    models.CharField(max_length=30, verbose_name="Instrumento en GDE"),
                ),
                (
                    "fecha_aplicacion",
                    models.DateField(verbose_name="Fecha de aplicación"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("0", "Plan de Trabajo Original"),
                            ("1", "Nuevo Plan de Trabajo"),
                        ],
                        default="0",
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "nro_plan",
                    models.PositiveIntegerField(default=1, verbose_name="Nro. Plan"),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.obras",
                        verbose_name="Obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispo. Plan de Trabajo",
                "verbose_name_plural": "Dispos. Plan de Trabajo",
                "ordering": ["obra"],
            },
        ),
    ]
