# Generated by Django 5.0.1 on 2024-03-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0017_remove_presupuestossubrubros_precio_rubro_oferta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="precio_total_oferta",
            field=models.FloatField(blank=True, null=True, verbose_name="Precio Total"),
        ),
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="precio_total_presupuesto",
            field=models.FloatField(blank=True, null=True, verbose_name="Precio Total"),
        ),
    ]
