# Generated by Django 5.0.1 on 2024-03-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0020_alter_presupuestossubrubros_unidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectores",
            name="fullname",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=200,
                null=True,
                verbose_name="Inspector",
            ),
        ),
    ]
