# Generated by Django 5.0.1 on 2024-07-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0020_plantrabajo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantrabajo",
            name="uvisAcumEsperados",
            field=models.PositiveIntegerField(
                default=0, verbose_name="UVIS Acum. Esperados"
            ),
        ),
    ]
