# Generated by Django 5.0.1 on 2024-03-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0021_inspectores_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="incidencias_oferta",
            field=models.FloatField(blank=True, null=True, verbose_name="Incidencias"),
        ),
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="precio_unitario_oferta",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Precio Unitario"
            ),
        ),
    ]
