# Generated by Django 5.0.1 on 2024-07-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0021_alter_plantrabajo_uvisacumesperados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantrabajo",
            name="uvisAcumEsperados",
            field=models.FloatField(default=0, verbose_name="UVIS Acum. Esperados"),
        ),
        migrations.AlterField(
            model_name="plantrabajo",
            name="uvisEsperados",
            field=models.FloatField(verbose_name="UVIS Esperados"),
        ),
    ]
