# Generated by Django 5.0.1 on 2024-03-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0022_alter_presupuestossubrubros_incidencias_oferta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuestos",
            name="codPresupuesto",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=200,
                null=True,
                verbose_name="Cod. Presupuesto",
            ),
        ),
    ]
