# Generated by Django 5.0.1 on 2024-07-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0023_remove_obras_inicio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obras",
            name="plazo",
        ),
        migrations.AddField(
            model_name="obras",
            name="plazoNro",
            field=models.IntegerField(default=0, verbose_name="Plazo Contractual"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="obras",
            name="plazoTipo",
            field=models.CharField(
                choices=[("0", "Días"), ("1", "Meses"), ("2", "Años")],
                default="0",
                max_length=1,
                verbose_name="Unidad de Tiempo",
            ),
        ),
    ]
