# Generated by Django 5.0.1 on 2024-03-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0024_remove_presupuestos_codpresupuesto_obras_codobra"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subrubros",
            options={
                "ordering": ["rubro", "name"],
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
        migrations.AlterField(
            model_name="subrubros",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Item"),
        ),
    ]
