# Generated by Django 5.0.1 on 2024-03-08 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0025_alter_subrubros_options_alter_subrubros_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="subrubro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.subrubros",
                verbose_name="Item",
            ),
        ),
    ]
