# Generated by Django 5.0.1 on 2024-07-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0025_dispoparalizacion_delete_actasobras_delete_actatipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispoparalizacion",
            name="dispo",
            field=models.CharField(
                default=0, max_length=30, verbose_name="Disposición de paralización"
            ),
            preserve_default=False,
        ),
    ]
