# Generated by Django 5.0.1 on 2024-07-21 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0026_dispoparalizacion_dispo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispoReinicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispo",
                    models.CharField(
                        max_length=30, verbose_name="Disposición de reinicio"
                    ),
                ),
                ("fecha_reinicio", models.DateField(verbose_name="Fecha de reinicio")),
                (
                    "dias_pendientes",
                    models.IntegerField(default=0, verbose_name="Días pendientes"),
                ),
                (
                    "nueva_vencimiento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Nueva Fecha de Vencimiento Contractual",
                    ),
                ),
                (
                    "dispo_para",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.dispoparalizacion",
                        verbose_name="Disposición de Paralización",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cargado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disposición de reinicio",
                "verbose_name_plural": "Disposiciones de reinicio",
                "ordering": ["dispo_para", "fecha_reinicio"],
            },
        ),
    ]
