# Generated by Django 5.0.1 on 2024-07-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0028_rename_dias_pendientes_disporeinicio_dias_pend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantrabajo",
            name="ultimo",
            field=models.BooleanField(default=False, verbose_name="Ultimo Periodo"),
        ),
    ]
