# Generated by Django 5.0.1 on 2024-03-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0028_alter_presupuestossubrubros_uvi_oferta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="uvi_oferta",
            field=models.FloatField(blank=True, null=True, verbose_name="Uvi"),
        ),
    ]
