# Generated by Django 5.0.1 on 2024-03-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0030_alter_presupuestossubrubros_precio_unitario_oferta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="incidencias_oferta",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="Incidencias"
            ),
        ),
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="incidencias_presupuesto",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="Incidencias"
            ),
        ),
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="precio_total_oferta",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="Precio Total"
            ),
        ),
        migrations.AlterField(
            model_name="presupuestossubrubros",
            name="precio_total_presupuesto",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="Precio Total"
            ),
        ),
    ]
