# Generated by Django 5.0.1 on 2024-03-10 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0032_alter_presupuestossubrubros_uvi_oferta"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ofertas",
        ),
    ]
