# Generated by Django 5.0.1 on 2024-03-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0035_estados_obras_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="obras",
            name="acta_inicio",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Acta inicio"
            ),
        ),
    ]
