# Generated by Django 5.0.1 on 2024-04-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0036_obras_acta_inicio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obras",
            name="estado",
        ),
        migrations.AddField(
            model_name="obras",
            name="expedientes",
            field=models.CharField(default=0, max_length=20, verbose_name="Expediente"),
            preserve_default=False,
        ),
    ]
