# Generated by Django 5.0.1 on 2024-05-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0037_remove_obras_estado_obras_expedientes"),
    ]

    operations = [
        migrations.AddField(
            model_name="obras",
            name="acta_ampliacion_1",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Acta ampliacion N°1"
            ),
        ),
        migrations.AddField(
            model_name="obras",
            name="acta_ampliacion_2",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Acta ampliacion N°2"
            ),
        ),
        migrations.AddField(
            model_name="obras",
            name="fecha_cotrato",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de contrato"
            ),
        ),
        migrations.AddField(
            model_name="obras",
            name="monto_contrato",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Monto de contrato ($)"
            ),
        ),
        migrations.AddField(
            model_name="obras",
            name="monto_uvi",
            field=models.FloatField(default=0, verbose_name="Monto de contrato (UVIS)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="obras",
            name="nombre_obra",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Obra"
            ),
        ),
        migrations.AddField(
            model_name="obras",
            name="valor_uvi_contrato",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="Valor UVI contrato"
            ),
        ),
    ]
