# Generated by Django 5.0.1 on 2024-05-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0038_obras_acta_ampliacion_1_obras_acta_ampliacion_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obras",
            name="monto_uvi",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Monto de contrato (UVIS)"
            ),
        ),
    ]
