# Generated by Django 5.0.1 on 2024-05-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0040_alter_obras_vencimiento_contractual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obras",
            name="valor_uvi_contrato",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Valor UVI contrato"
            ),
        ),
        migrations.AlterField(
            model_name="obras",
            name="vencimiento_ampliacion_1",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Vencimiento 1ra Ampliación Contractual",
            ),
        ),
        migrations.AlterField(
            model_name="obras",
            name="vencimiento_ampliacion_2",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Vencimiento 2da Ampliación Contractual",
            ),
        ),
    ]
