# Generated by Django 5.0.1 on 2024-05-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0041_alter_obras_valor_uvi_contrato_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obras",
            name="acta_ampliacion_1",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Acta ampliacion N°1"
            ),
        ),
        migrations.AlterField(
            model_name="obras",
            name="acta_ampliacion_2",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Acta ampliacion N°2"
            ),
        ),
        migrations.AlterField(
            model_name="obras",
            name="acta_inicio",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Acta inicio"
            ),
        ),
        migrations.AlterField(
            model_name="obras",
            name="expedientes",
            field=models.CharField(max_length=30, verbose_name="Expediente"),
        ),
    ]
