# Generated by Django 5.0.1 on 2024-05-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0042_alter_obras_acta_ampliacion_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obras",
            name="nombre_obra",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Obra"
            ),
        ),
    ]
