# Generated by Django 5.0.1 on 2024-05-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0043_alter_obras_nombre_obra"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpresaPoliza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa",
                    models.CharField(
                        max_length=50, verbose_name="Nombre de empresa aseguradora"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Domicilio"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Teléfono"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["empresa"],
            },
        ),
        migrations.AddField(
            model_name="obras",
            name="acta_fondo_reparo",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Acta póliza sustitución Fondo de Reparo",
            ),
        ),
        migrations.AddField(
            model_name="obras",
            name="poliza_sustitucion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="N° Póliza Fondo de Reparo"
            ),
        ),
        migrations.AddField(
            model_name="obras",
            name="empresa_poliza",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.empresapoliza",
                verbose_name="Empresa aseguradora",
            ),
        ),
    ]
