# Generated by Django 5.0.1 on 2024-05-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0045_empresapoliza_creaempresa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresapoliza",
            options={
                "ordering": ["empresa"],
                "verbose_name": "Aseguradora",
                "verbose_name_plural": "Aseguradoras",
            },
        ),
    ]
