# Generated by Django 5.0.1 on 2024-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0052_alter_empresapoliza_creaempresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obras",
            name="nombre_obra",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Carátula Obra"
            ),
        ),
    ]
