# Generated by Django 5.0.1 on 2024-05-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0053_alter_obras_nombre_obra"),
    ]

    operations = [
        migrations.AddField(
            model_name="obras",
            name="tiene_poliza",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Presenta póliza de sustitución?"
            ),
        ),
    ]
