# Generated by Django 5.0.1 on 2024-05-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0054_obras_tiene_poliza"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nro_cert",
                    models.PositiveIntegerField(verbose_name="Certificado N°"),
                ),
                ("fecha", models.DateField(verbose_name="Fecha certificado")),
                ("uvi", models.FloatField(verbose_name="Cant UVIs certificados")),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.obras",
                        verbose_name="Obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["obra", "nro_cert"],
            },
        ),
    ]
