# Generated by Django 5.0.1 on 2024-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0057_alter_certificados_cargacert"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificados",
            name="codCert",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=200,
                null=True,
                verbose_name="Cod. Obra",
            ),
        ),
    ]
