# Generated by Django 5.0.1 on 2024-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0059_alter_certificados_codcert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificados",
            name="codCert",
            field=models.CharField(
                editable=False,
                max_length=200,
                unique=True,
                verbose_name="Cod. Certificado",
            ),
        ),
    ]
