# Generated by Django 5.0.1 on 2024-05-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0060_alter_certificados_codcert"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificados",
            name="fecha_acta",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de presentación de Acta"
            ),
        ),
    ]
