# Generated by Django 5.0.1 on 2024-05-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0061_certificados_fecha_acta"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificados",
            name="periodo",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Periodo medido"
            ),
        ),
        migrations.AlterField(
            model_name="certificados",
            name="fecha",
            field=models.DateField(verbose_name="Fecha del certificado"),
        ),
        migrations.AlterField(
            model_name="certificados",
            name="fecha_acta",
            field=models.DateField(
                blank=True, null=True, verbose_name="Presenta Acta Inspector"
            ),
        ),
    ]
