# Generated by Django 5.0.1 on 2024-05-08 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0063_alter_certificados_periodo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActaTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tipo de Acta")),
            ],
            options={
                "verbose_name": "Tipo de Acta",
                "verbose_name_plural": "Tipos de Actas",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="obras",
            name="acta_ampliacion_1",
        ),
        migrations.RemoveField(
            model_name="obras",
            name="acta_ampliacion_2",
        ),
        migrations.RemoveField(
            model_name="obras",
            name="acta_inicio",
        ),
        migrations.RemoveField(
            model_name="obras",
            name="ampliacion_1",
        ),
        migrations.RemoveField(
            model_name="obras",
            name="ampliacion_2",
        ),
        migrations.RemoveField(
            model_name="obras",
            name="vencimiento_ampliacion_1",
        ),
        migrations.RemoveField(
            model_name="obras",
            name="vencimiento_ampliacion_2",
        ),
        migrations.CreateModel(
            name="ActasObras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha aplicación Acta"
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(default=1, verbose_name="Nro Orden"),
                ),
                (
                    "dispo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Disposición",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.obras",
                        verbose_name="Obra",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.actatipo",
                        verbose_name="Tipo de Acta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta",
                "verbose_name_plural": "Actas",
                "ordering": ["obra"],
            },
        ),
    ]
