# Generated by Django 5.0.1 on 2024-05-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0064_actatipo_remove_obras_acta_ampliacion_1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actasobras",
            options={
                "ordering": ["obra"],
                "verbose_name": "Acta obra",
                "verbose_name_plural": "Actas obras",
            },
        ),
        migrations.AddField(
            model_name="actasobras",
            name="codActa",
            field=models.CharField(
                editable=False,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Cod. Acta",
            ),
        ),
    ]
