# Generated by Django 5.0.1 on 2024-05-11 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0065_alter_actasobras_options_actasobras_codacta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obras",
            name="acta_fondo_reparo",
        ),
        migrations.RemoveField(
            model_name="obras",
            name="empresa_poliza",
        ),
        migrations.RemoveField(
            model_name="obras",
            name="poliza_sustitucion",
        ),
        migrations.RemoveField(
            model_name="obras",
            name="tiene_poliza",
        ),
        migrations.CreateModel(
            name="Polizas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tiene_poliza",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Presenta póliza de sustitución?",
                    ),
                ),
                (
                    "acta_fondo_reparo",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Póliza de sustitución Fondo de Reparo",
                    ),
                ),
                (
                    "poliza_sustitucion",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="N° Póliza Fondo de Reparo"
                    ),
                ),
                (
                    "monto_asegurado",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Monto asegurado"
                    ),
                ),
                (
                    "obervacion",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                (
                    "empresa_poliza",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mioc.empresapoliza",
                        verbose_name="Empresa aseguradora",
                    ),
                ),
            ],
        ),
    ]
