# Generated by Django 5.0.1 on 2024-05-11 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0066_remove_obras_acta_fondo_reparo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="polizas",
            name="obra",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.obras",
                verbose_name="Obra",
            ),
            preserve_default=False,
        ),
    ]
