# Generated by Django 5.0.1 on 2024-05-12 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0070_alter_polizas_user_memorias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="memorias",
            name="codMem",
            field=models.CharField(
                default=0,
                editable=False,
                max_length=200,
                unique=True,
                verbose_name="Cod. Memoria",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memorias",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cargado por",
            ),
        ),
    ]
