# Generated by Django 5.0.1 on 2024-05-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0071_memorias_codmem_memorias_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorias",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Imagen"
            ),
        ),
    ]
