# Generated by Django 5.0.1 on 2024-05-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0072_memorias_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memorias",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images", verbose_name="Imagen"
            ),
        ),
    ]
