# Generated by Django 5.0.1 on 2024-05-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0073_alter_memorias_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obras",
            name="inspector",
        ),
    ]
