# Generated by Django 5.0.1 on 2024-05-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0075_dispoinspector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispoinspector",
            name="inspector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mioc.inspectores",
                verbose_name="Inspector",
            ),
        ),
    ]
