# Generated by Django 5.0.1 on 2024-05-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0076_alter_dispoinspector_inspector"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispoinspector",
            name="dispo",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Disposición"
            ),
        ),
    ]
