# Generated by Django 5.0.1 on 2024-05-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0077_dispoinspector_dispo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispoinspector",
            name="dispo",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Disposición"
            ),
        ),
    ]
