# Generated by Django 5.0.1 on 2024-05-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0078_alter_dispoinspector_dispo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispoinspector",
            name="dispo",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Disposición"
            ),
        ),
    ]
