# Generated by Django 5.0.1 on 2024-05-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0079_alter_dispoinspector_dispo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispoinspector",
            name="dispo",
            field=models.CharField(max_length=30, verbose_name="Disposición"),
        ),
    ]
