# Generated by Django 5.0.1 on 2024-05-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0081_dispoinspector_observacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispoinspector",
            name="fecha",
            field=models.DateField(verbose_name="Fecha"),
        ),
    ]
