# Generated by Django 5.0.1 on 2024-05-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0082_alter_dispoinspector_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificados",
            name="uvi_acum",
            field=models.FloatField(default=0, verbose_name="Cant UVIs acumulados"),
        ),
        migrations.AlterField(
            model_name="certificados",
            name="fecha_acta",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha que presenta Acta el Inspector",
            ),
        ),
    ]
