# Generated by Django 5.0.1 on 2024-05-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0083_certificados_uvi_acum_alter_certificados_fecha_acta"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificados",
            name="avance_acum_med",
            field=models.FloatField(default=0, verbose_name="Avance real (%)"),
        ),
        migrations.AddField(
            model_name="certificados",
            name="avance_acum_proy",
            field=models.FloatField(default=0, verbose_name="Avance proyectado (%)"),
        ),
    ]
