# Generated by Django 5.0.1 on 2024-05-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mioc", "0084_certificados_avance_acum_med_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificados",
            name="coef_avance",
            field=models.CharField(
                default=0, max_length=15, verbose_name="Coef. Avance (%)"
            ),
        ),
    ]
